### ISSUE TITLE
Update tests to use standalone factory and assertion DB sessions

### ISSUE THREAD

**Issue by marksparkza** [SAEON/sadco-server#3]
Test object factories (and any additional test function- or fixture-specific DB setup) should use a standalone `FactorySession` instance initialized in the `factories` module.

Any post-evaluation queries which make assertions about database state (e.g. in the `test_db` module) should use a standalone `TestSession` instance initialized in the top level test package.

See https://github.com/SAEON/odp-server/issues/27 for further discussion around this change.

For reference, see the changes to ODP server test code in https://github.com/SAEON/odp-server/commit/cc6614f11e0889dfb03d9f69bedaa88a0919c190

**Comment by dylanpivo** [comment]
Completed as per this [commit](https://github.com/SAEON/sadco-server/commit/e44eb4e7bb931f2c8788f27dd3992b0342f5aa8d)
